export interface Listing {
  id: string
  slug: string
  title: string
  price: number          // 0 = contact for pricing
  beds: number
  baths: number
  sqft: number
  year: number
  type: 'new' | 'repo'
  wideType?: 'Single Wide' | 'Double Wide' | 'Triple Wide'
  region: 'South TX' | 'Central TX' | 'West TX' | 'North TX' | 'East TX'
  city: string
  images: string[]
  features: string[]
  description: string
  monthlyPayment: number
  downPayment: number
  available: boolean
  hudCertified: boolean
  featured?: boolean
  manufacturer?: string
  model?: string
  dimensions?: string
  matterportUrl?: string
  notionId?: string
  status?: 'Active' | 'Pending' | 'Sold' | 'Coming Soon' | 'Repo Deal'
  floorplanUrl?: string
}

export const sampleListings: Listing[] = [
  // ─── BMH-1 · The Pigeon ────────────────────────────────────────────
  {
    id: 'BMH-1',
    slug: 'marathon-pigeon-3bed-2bath-double-wide',
    title: 'The Pigeon',
    manufacturer: 'Texas Homes Direct',
    model: 'Archer',
    dimensions: '28x44',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1232,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-pigeon/Marathon-Archer-7.jpeg',
      '/homes/the-pigeon/Marathon-Archer-1.jpeg',
      '/homes/the-pigeon/Marathon-Archer-3.jpeg',
      '/homes/the-pigeon/Marathon-Archer-4.jpeg',
      '/homes/the-pigeon/Marathon-Archer-6.jpeg',
      '/homes/the-pigeon/Marathon-Archer-5.jpeg',
      '/homes/the-pigeon/Marathon-Archer-8.jpeg',
      '/homes/the-pigeon/Marathon-Archer-2_(1).jpeg',
    ],
    features: ['Open Concept', 'Kitchen Island', 'Walk-in Closet', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Pigeon is a well-designed doublewide manufactured home offering approximately 1,232 square feet of living space, featuring three bedrooms and two bathrooms in a practical single-story layout. Its open-concept design connects the living, dining, and kitchen areas to create an easy flow for everyday living and entertaining, while the centrally located kitchen serves as a functional hub.',
    monthlyPayment: 1250,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: undefined,
    floorplanUrl: '/homes/floorplans/Pigeon-FloorPlan.png',
  },

  // ─── BMH-14 · The Dove ─────────────────────────────────────────────
  {
    id: 'BMH-14',
    slug: 'marathon-dove-1bed-1bath-single-wide',
    title: 'The Dove',
    manufacturer: 'Texas Homes Direct',
    model: 'Dove',
    dimensions: '16x40',
    price: 0,
    beds: 1,
    baths: 1,
    sqft: 472,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-dove/Dove-Hero.png',
      '/homes/the-dove/IMG_0895.jpg.jpeg',
      '/homes/the-dove/IMG_0079-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0074-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0069-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0064-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0059-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0054-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0044-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0036-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0034-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0019-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0006-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0004-scaled.jpg.jpeg',
      '/homes/the-dove/cfdc3b97-c652-4392-a7d9-e9393520a4ff-scaled.jpg.jpeg',
      '/homes/the-dove/446a0c32-a24b-4392-9be3-facc862a29be-scaled.jpg.jpeg',
    ],
    features: ['Compact and Efficient', 'Starter Home', 'Affordable Entry Point', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Dove is a charming and compact single-wide manufactured home that makes smart, efficient use of 472 square feet. Perfect as a starter home or for those seeking affordable, low-maintenance living in a 16x40 layout.',
    monthlyPayment: 930,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: true,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=bAQiAM7npui&back=1',
    floorplanUrl: '/homes/floorplans/Dove-FloorPlan.jpeg',
  },

  // ─── BMH-15 · The Gadwall ──────────────────────────────────────────
  {
    id: 'BMH-15',
    slug: 'marathon-gadwall-3bed-2bath-double-wide',
    title: 'The Gadwall',
    manufacturer: 'Texas Homes Direct',
    model: 'Gadwall',
    dimensions: '32x56',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1680,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-gadwall/Gadwall-Hero.png',
      '/homes/the-gadwall/IMG_1787-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1786-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1785-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1784-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1783-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1782-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1780-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1778-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1777-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1775-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1773-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1772-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1771-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1770-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1769-2-scaled.jpg.jpeg',
    ],
    features: ['Open Concept', 'Double Wide', 'Spacious Layout', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Gadwall is a spacious and thoughtfully designed double-wide manufactured home that blends comfort with everyday functionality. At 32x56 and 1,680 sq. ft., it offers 3 bedrooms and 2 bathrooms for comfortable family living.',
    monthlyPayment: 1520,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: undefined,
    floorplanUrl: '/homes/floorplans/Gadwall-FloorPlan.jpeg',
  },

  // ─── BMH-16 · The Pintail ──────────────────────────────────────────
  {
    id: 'BMH-16',
    slug: 'marathon-pintail-4bed-2bath-double-wide',
    title: 'The Pintail',
    manufacturer: 'Texas Homes Direct',
    model: 'Pintail',
    dimensions: '32x64',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 1920,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-pintail/8-Sterling.png',
      '/homes/the-pintail/IMG_7053-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7054-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7056-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7057-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7060-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7061-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7064-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7066-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7068-scaled.jpg.jpeg',
    ],
    features: ['Spacious Layout', 'Open Concept', 'Stylish Finishes', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Pintail is a spacious and stylish manufactured home that thoughtfully combines comfort with modern design. At 32x64 and 1,920 sq. ft., this 4 bedroom, 2 bathroom double-wide delivers excellent space for growing families.',
    monthlyPayment: 1650,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: true,
    status: 'Active',
    matterportUrl: undefined,
    floorplanUrl: '/homes/floorplans/Pintail-FloorPlan.jpeg',
  },

  // ─── BMH-17 · The Spoonbill ────────────────────────────────────────
  {
    id: 'BMH-17',
    slug: 'marathon-spoonbill-3bed-2bath-single-wide',
    title: 'The Spoonbill',
    manufacturer: 'Texas Homes Direct',
    model: 'Spoonbill',
    dimensions: '16x76',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1140,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-spoonbill/Spoonbill-Hero.png',
      '/homes/the-spoonbill/IMG_7169-scaled.jpg.jpeg',
      '/homes/the-spoonbill/image-9-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7170-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7178-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7180-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7185-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7190-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7195-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7200-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7208-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7210-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7215-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7220-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7228-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7230-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7238-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7243-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7245-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7253-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7258-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7263-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7268-scaled.jpg.jpeg',
    ],
    features: ['Practical Layout', 'Single Wide', 'Comfortable Living', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Spoonbill is a beautifully balanced manufactured home that offers both comfort and practicality in a 16x76 single-wide layout. With 1,140 sq. ft., 3 bedrooms, and 2 bathrooms, it delivers solid value for first-time buyers.',
    monthlyPayment: 1050,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=aAk5oxt6cER&back=1',
    floorplanUrl: '/homes/floorplans/Spoonbill-FloorPlan.jpeg',
  },

  // ─── BMH-18 · The Redhead ──────────────────────────────────────────
  {
    id: 'BMH-18',
    slug: 'marathon-redhead-3bed-2bath-double-wide',
    title: 'The Redhead',
    manufacturer: 'Texas Homes Direct',
    model: 'Redhead',
    dimensions: '32x56',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1680,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-redhead/IMG_0001-scaled.jpg.jpeg',
      '/homes/the-redhead/3ba5543a-6344-4c4d-8af4-a6c8f13c2ce3-scaled.jpg.jpeg',
      '/homes/the-redhead/9cef5aa3-21fd-49df-9f5b-f29d499eb038-scaled.jpg.jpeg',
      '/homes/the-redhead/99a8b129-48eb-4506-8848-37d730ac1e89-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0002-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0009-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0014-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0019-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0029-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0039-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0044-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0049-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0054-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0059-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0064-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0069-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0074-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0079-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0084-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0094-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0099-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0104-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0114-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0116-scaled.jpg.jpeg',
    ],
    features: ['Open Concept', 'Double Wide', 'Spacious Bedrooms', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Redhead is a beautifully crafted manufactured home that combines spacious, thoughtful design with modern comfort. At 32x56 and 1,680 sq. ft., this 3 bedroom, 2 bathroom double-wide is built for families who want quality without compromise.',
    monthlyPayment: 1520,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=7VkF3t1HMLY&back=1',
    floorplanUrl: '/homes/floorplans/Redhead-FloorPlan.jpeg',
  },

  // ─── BMH-19 · The Wood Duck ────────────────────────────────────────
  {
    id: 'BMH-19',
    slug: 'marathon-woodduck-3bed-2bath-double-wide',
    title: 'The Wood Duck',
    manufacturer: 'Texas Homes Direct',
    model: 'Wood Duck',
    dimensions: '32x56',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1680,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-coleman/Coleman-Gallery-1.jpg',
      '/homes/the-wood-duck/IMG_0579-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0584-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0589-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0597-scaled.jpg.jpeg',
      '/homes/the-wood-duck/IMG_0602-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0607-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0609-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0614-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0622-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0627-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0632-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0637-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0642-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0647-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0657-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0662-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0667-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0669-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0677-scaled.jpeg',
    ],
    features: ['Open Concept', 'Double Wide', 'Inviting Layout', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Wood Duck is a thoughtfully designed double-wide manufactured home that offers an inviting layout with 3 bedrooms, 2 bathrooms, and 1,680 sq. ft. of living space in a 32x56 footprint.',
    monthlyPayment: 1490,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=XZ7JAYuj8K9&back=1',
    floorplanUrl: '/homes/floorplans/WoodDuck-FloorPlan.jpeg',
  },

  // ─── BMH-20 · The Widgeon ──────────────────────────────────────────
  {
    id: 'BMH-20',
    slug: 'marathon-widgeon-4bed-2bath-double-wide',
    title: 'The Widgeon',
    manufacturer: 'Texas Homes Direct',
    model: 'Widgeon',
    dimensions: '32x68',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 2040,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-widgeon/2-Stonewall.jpg.jpeg',
      '/homes/the-widgeon/IMG_0682-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0687-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0692-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0697-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0702-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0707-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0712-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0717-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0722-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0724-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0732-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0737-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0739-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0744-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0749-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0757-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0762-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0767-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0769-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0774-scaled.jpg.jpeg',
    ],
    features: ['Spacious Layout', 'Open Concept', 'Double Wide', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Widgeon is a spacious, thoughtfully designed double-wide manufactured home that blends comfort with functionality. With 2,040 sq. ft., 4 bedrooms, and 2 bathrooms in a 32x68 layout, it has plenty of room for the whole family.',
    monthlyPayment: 1700,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=eLwoi66X6qK&back=1',
    floorplanUrl: '/homes/floorplans/Widgeon-FloorPlan.jpeg',
  },

  // ─── BMH-21 · The Mallard ──────────────────────────────────────────
  {
    id: 'BMH-21',
    slug: 'marathon-mallard-4bed-2bath-double-wide',
    title: 'The Mallard',
    manufacturer: 'Texas Homes Direct',
    model: 'Mallard',
    dimensions: '32x76',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 2280,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-mallard/213CCA81-EDC0-4C8C-8804-8B2ACE3E4731.jpg.jpeg',
      '/homes/the-mallard/1a65e343-b855-4512-bad8-199f089d0ff4-scaled.jpg.jpeg',
      '/homes/the-mallard/aaed3281-a103-4cd9-befa-83003f52c769-scaled.jpg.jpeg',
      '/homes/the-mallard/baa0f374-8e96-46a2-ac32-94d1c41b14e4-scaled.jpg.jpeg',
      '/homes/the-mallard/e4abc9c0-8038-408c-bbf1-7d1363c35de3-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0217-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0225-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0230-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0235-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0240-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0242-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0247-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0252-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0257-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0262-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0267-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0275-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0277-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0285-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0287-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0292-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0297-scaled.jpg.jpeg',
    ],
    features: ['Generous Layout', 'Open Concept', 'Large Double Wide', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Mallard from Texas Homes Direct is a generous double-wide layout measuring 32x76 feet with 2,280 sq. ft. of living space. Four bedrooms and two bathrooms give families all the room they need.',
    monthlyPayment: 1750,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: true,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=XGZhqhubvVW&back=1',
    floorplanUrl: '/homes/floorplans/Mallard-FloorPlan.jpeg',
  },


  // ─── BMH-22 · The Coleman ─────────────────────────────────────────────
  {
    id: 'BMH-22',
    slug: 'marathon-coleman-3bed-2bath-double-wide',
    title: 'The Coleman',
    manufacturer: 'Texas Homes Direct',
    model: 'Coleman',
    dimensions: '28x60',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1531,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-wood-duck/Wood-Duck-Hero.png',
      '/homes/the-coleman/Coleman-Updated-Photo.webp',
      '/homes/the-coleman/Coleman-Gallery-2.webp',
      '/homes/the-coleman/Coleman-Gallery-3.webp',
      '/homes/the-coleman/Coleman-Gallery-4.webp',
      '/homes/the-coleman/Coleman-Gallery-5.webp',
      '/homes/the-coleman/Coleman-Gallery-6.webp',
      '/homes/the-coleman/Coleman-Gallery-7.webp',
      '/homes/the-coleman/Coleman-Gallery-8.webp',
    ],
    features: ['4th Bedroom Option', '3rd Bathroom Option', '3 Bed / 2 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Coleman is a 28x60 doublewide with 1,531 square feet, 3 beds and 2 baths. 4th bedroom and 3rd bathroom options available.',
    monthlyPayment: 1500,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Coleman-FloorPlan.webp',
  },
  // ─── BMH-23 · The Amarillo ─────────────────────────────────────────────
  {
    id: 'BMH-23',
    slug: 'marathon-amarillo-2bed-2bath-single-wide',
    title: 'The Amarillo',
    manufacturer: 'Texas Homes Direct',
    model: 'Amarillo',
    dimensions: '14x60',
    price: 0,
    beds: 2,
    baths: 2,
    sqft: 820,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Amarillo-FloorPlan.webp',
    ],
    features: ['2 Bed / 2 Bath', '820 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Amarillo is a 14x60 singlewide with 820 square feet, 2 beds and 2 baths. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 900,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Amarillo-FloorPlan.webp',
  },
  // ─── BMH-24 · The Loving ─────────────────────────────────────────────
  {
    id: 'BMH-24',
    slug: 'marathon-loving-3bed-2bath-double-wide',
    title: 'The Loving',
    manufacturer: 'Texas Homes Direct',
    model: 'Loving',
    dimensions: '32x56',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1680,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Loving-FloorPlan.webp',
    ],
    features: ['Primary Bath Option', 'Transom Windows Option', '3 Bed / 2 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Loving is a 32x56 doublewide with 1,680 square feet, 3 beds and 2 baths. Primary bath and transom window options. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 1490,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Loving-FloorPlan.webp',
  },
  // ─── BMH-25 · The Conroe ─────────────────────────────────────────────
  {
    id: 'BMH-25',
    slug: 'marathon-conroe-2bed-2bath-single-wide',
    title: 'The Conroe',
    manufacturer: 'Texas Homes Direct',
    model: 'Conroe',
    dimensions: '16x56',
    price: 0,
    beds: 2,
    baths: 2,
    sqft: 840,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Conroe-FloorPlan.webp',
    ],
    features: ['2 Bed / 2 Bath', '840 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Conroe is a 16x56 singlewide with 840 square feet, 2 beds and 2 baths. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 850,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Conroe-FloorPlan.webp',
  },
  // ─── BMH-26 · The Katy ─────────────────────────────────────────────
  {
    id: 'BMH-26',
    slug: 'marathon-katy-3bed-2bath-single-wide',
    title: 'The Katy',
    manufacturer: 'Texas Homes Direct',
    model: 'Katy',
    dimensions: '16x68',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1020,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-katy/Katy-Hero.png',
      '/homes/the-katy/katy-interior-01.jpg',
      '/homes/the-katy/katy-interior-02.jpg',
      '/homes/the-katy/katy-interior-03.jpg',
      '/homes/the-katy/katy-interior-04.jpg',
      '/homes/the-katy/katy-interior-05.jpg',
      '/homes/the-katy/katy-interior-06.jpg',
      '/homes/the-katy/katy-interior-07.jpg',
      '/homes/the-katy/katy-interior-08.jpg',
      '/homes/the-katy/katy-interior-09.jpg',
      '/homes/the-katy/katy-interior-10.jpg',
    ],
    features: ['3 Bed / 2 Bath', '1,020 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Katy is a 16x68 singlewide with 1,020 square feet, 3 beds and 2 baths.',
    monthlyPayment: 950,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Katy-FloorPlan.webp',
  },
  // ─── BMH-27 · The Jasper ─────────────────────────────────────────────
  {
    id: 'BMH-27',
    slug: 'marathon-jasper-3bed-2bath-double-wide',
    title: 'The Jasper',
    manufacturer: 'Texas Homes Direct',
    model: 'Jasper',
    dimensions: '32x48',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1440,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Jasper-FloorPlan.webp',
    ],
    features: ['3 Bed / 2 Bath', '1,440 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Jasper is a 32x48 doublewide with 1,440 square feet, 3 beds and 2 baths. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 1375,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Jasper-FloorPlan.webp',
  },
  // ─── BMH-28 · The Hays ─────────────────────────────────────────────
  {
    id: 'BMH-28',
    slug: 'marathon-hays-4bed-2bath-double-wide',
    title: 'The Hays',
    manufacturer: 'Texas Homes Direct',
    model: 'Hays',
    dimensions: '28x76',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 2077,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Hays-FloorPlan.webp',
    ],
    features: ['3rd Bathroom Option', '4 Bed / 2 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Hays is a 28x76 doublewide with 2,077 square feet, 4 beds and 2 baths. 3rd bathroom option. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 1700,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Hays-FloorPlan.webp',
  },
  // ─── BMH-29 · The Mesquite ─────────────────────────────────────────────
  {
    id: 'BMH-29',
    slug: 'marathon-mesquite-3bed-2bath-single-wide',
    title: 'The Mesquite',
    manufacturer: 'Texas Homes Direct',
    model: 'Mesquite',
    dimensions: '16x76',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1140,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-mesquite/Mesquite-Body-1.png',
      '/homes/the-mesquite/Mesquite-Body-2.webp',
      '/homes/the-mesquite/Mesquite-Body-3.webp',
      '/homes/the-mesquite/Mesquite-Body-4.webp',
      '/homes/the-mesquite/Mesquite-Body-5.webp',
      '/homes/the-mesquite/Mesquite-Body-6.webp',
      '/homes/the-mesquite/Mesquite-Body-7.webp',
      '/homes/the-mesquite/Mesquite-Body-8.webp',
      '/homes/the-mesquite/Mesquite-Body-9.webp',
      '/homes/the-mesquite/Mesquite-Body-10.webp',
      '/homes/the-mesquite/Mesquite-Body-11.webp',
      '/homes/the-mesquite/Mesquite-Body-12.webp',
      '/homes/the-mesquite/Mesquite-Body-13.webp',
      '/homes/the-mesquite/Mesquite-Body-14.webp',
    ],
    features: ['3 Bed / 2 Bath', '1,140 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Mesquite is a 16x76 singlewide with 1,140 square feet, 3 beds and 2 baths.',
    monthlyPayment: 950,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Mesquite-FloorPlan.webp',
  },
  // ─── BMH-30 · The Bell ─────────────────────────────────────────────
  {
    id: 'BMH-30',
    slug: 'marathon-bell-3bed-2bath-double-wide',
    title: 'The Bell',
    manufacturer: 'Texas Homes Direct',
    model: 'Bell',
    dimensions: '28x52',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1421,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Bell-FloorPlan.webp',
    ],
    features: ['3 Bed / 2 Bath', '1,421 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Bell is a 28x52 doublewide with 1,421 square feet, 3 beds and 2 baths. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 1300,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Bell-FloorPlan.webp',
  },
  // ─── BMH-31 · The Terra ─────────────────────────────────────────────
  {
    id: 'BMH-31',
    slug: 'marathon-terra-2bed-1bath-park-model',
    title: 'The Terra',
    manufacturer: 'Texas Homes Direct',
    model: 'Terra',
    dimensions: '12x33',
    price: 0,
    beds: 2,
    baths: 1,
    sqft: 396,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-terra/Terra-Hero.png',
      '/homes/the-terra/terra1-1.webp',
      '/homes/the-terra/terra-2.webp',
      '/homes/the-terra/terra-3.webp',
      '/homes/the-terra/terra-4.webp',
      '/homes/the-terra/terra-5.webp',
      '/homes/the-terra/terra-6.webp',
    ],
    features: ['Park Model/Tiny Home', '2 Bed / 1 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Terra is a 12x33 park model / tiny home, 396 square feet, 2 beds and 1 bath.',
    monthlyPayment: 800,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Terra-FloorPlan.webp',
  },
  // ─── BMH-32 · The Brewster ─────────────────────────────────────────────
  {
    id: 'BMH-32',
    slug: 'marathon-brewster-3bed-2bath-double-wide',
    title: 'The Brewster',
    manufacturer: 'Texas Homes Direct',
    model: 'Brewster',
    dimensions: '28x56',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1531,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-brewster/Brewster-Body-1.jpg',
      '/homes/the-brewster/Brewster-Body-2.png',
      '/homes/the-brewster/Brewster-Body-3.webp',
      '/homes/the-brewster/Brewster-Body-4.webp',
      '/homes/the-brewster/Brewster-Body-5.webp',
      '/homes/the-brewster/Brewster-Body-6.webp',
      '/homes/the-brewster/Brewster-Body-7.webp',
      '/homes/the-brewster/Brewster-Body-8.webp',
    ],
    features: ['4th Bedroom Option', '3 Bed / 2 Bath', '1,531 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Brewster is a 28x56 doublewide with 1,531 square feet, 3 beds and 2 baths. 4th bedroom option available.',
    monthlyPayment: 1400,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Brewster-FloorPlan.webp',
  },
  // ─── BMH-33 · The Caldwell ─────────────────────────────────────────────
  {
    id: 'BMH-33',
    slug: 'marathon-caldwell-4bed-2bath-double-wide',
    title: 'The Caldwell',
    manufacturer: 'Texas Homes Direct',
    model: 'Caldwell',
    dimensions: '28x56',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 1531,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Caldwell-FloorPlan.webp',
    ],
    features: ['Flex Room Option', '4 Bed / 2 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Caldwell is a 28x56 doublewide with 1,531 square feet, 4 beds and 2 baths. Flex room option. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 1350,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Caldwell-FloorPlan.webp',
  },
  // ─── BMH-34 · The Trinity ─────────────────────────────────────────────
  {
    id: 'BMH-34',
    slug: 'marathon-trinity-4bed-2bath-double-wide',
    title: 'The Trinity',
    manufacturer: 'Texas Homes Direct',
    model: 'Trinity',
    dimensions: '32x76',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 2280,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Trinity-FloorPlan.webp',
    ],
    features: ['4 Bed / 2 Bath', '2,280 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Trinity is a 32x76 doublewide with 2,280 square feet, 4 beds and 2 baths. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 1750,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Trinity-FloorPlan.webp',
  },
  // ─── BMH-35 · The Bailey ─────────────────────────────────────────────
  {
    id: 'BMH-35',
    slug: 'marathon-bailey-3bed-2bath-double-wide',
    title: 'The Bailey',
    manufacturer: 'Texas Homes Direct',
    model: 'Bailey',
    dimensions: '28x48',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1312,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Bailey-FloorPlan.webp',
    ],
    features: ['3 Bed / 2 Bath', '1,312 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Bailey is a 28x48 doublewide with 1,312 square feet, 3 beds and 2 baths. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 1200,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Bailey-FloorPlan.webp',
  },
  // ─── BMH-36 · The Kendall ─────────────────────────────────────────────
  {
    id: 'BMH-36',
    slug: 'marathon-kendall-3bed-2bath-double-wide',
    title: 'The Kendall',
    manufacturer: 'Texas Homes Direct',
    model: 'Kendall',
    dimensions: '32x52',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1560,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Kendall-FloorPlan.webp',
    ],
    features: ['Primary Bath Option', 'Transom Windows Option', '3 Bed / 2 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Kendall is a 32x52 doublewide with 1,560 square feet, 3 beds and 2 baths. Primary bath and transom window options. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 1400,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Kendall-FloorPlan.webp',
  },
  // ─── BMH-37 · The Grapevine ─────────────────────────────────────────────
  {
    id: 'BMH-37',
    slug: 'marathon-grapevine-2bed-2bath-single-wide',
    title: 'The Grapevine',
    manufacturer: 'Texas Homes Direct',
    model: 'Grapevine',
    dimensions: '16x60',
    price: 0,
    beds: 2,
    baths: 2,
    sqft: 900,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Grapevine-FloorPlan.webp',
    ],
    features: ['2 Bed / 2 Bath', '900 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Grapevine is a 16x60 singlewide with 900 square feet, 2 beds and 2 baths. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 850,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Grapevine-FloorPlan.webp',
  },
  // ─── BMH-38 · The Jackson ─────────────────────────────────────────────
  {
    id: 'BMH-38',
    slug: 'marathon-jackson-1bed-1bath-park-model',
    title: 'The Jackson',
    manufacturer: 'Texas Homes Direct',
    model: 'Jackson',
    dimensions: '12x33',
    price: 0,
    beds: 1,
    baths: 1,
    sqft: 396,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-jackson/Jackson-Body-1.png',
      '/homes/the-jackson/Jackson-Body-2.webp',
      '/homes/the-jackson/Jackson-Body-3.webp',
      '/homes/the-jackson/Jackson-Body-4.webp',
      '/homes/the-jackson/Jackson-Body-5.webp',
      '/homes/the-jackson/Jackson-Body-6.webp',
      '/homes/the-jackson/Jackson-Body-7.webp',
      '/homes/the-jackson/Jackson-Body-8.webp',
      '/homes/the-jackson/Jackson-Body-9.webp',
    ],
    features: ['Park Model/Tiny Home', 'Front Porch Option', '1 Bed / 1 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Jackson is a 12x33 park model / tiny home, 396 square feet, 1 bed and 1 bath. Front porch option available.',
    monthlyPayment: 800,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Jackson-FloorPlan.webp',
  },
  // ─── BMH-39 · The Abilene ─────────────────────────────────────────────
  {
    id: 'BMH-39',
    slug: 'marathon-abilene-2bed-1bath-single-wide',
    title: 'The Abilene',
    manufacturer: 'Texas Homes Direct',
    model: 'Abilene',
    dimensions: '14x56',
    price: 0,
    beds: 2,
    baths: 1,
    sqft: 765,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Abilene-FloorPlan.webp',
    ],
    features: ['2 Bed / 1 Bath', '765 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Abilene is a 14x56 singlewide with 765 square feet, 2 beds and 1 bath. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 800,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Abilene-FloorPlan.webp',
  },
  // ─── BMH-40 · The Ranger ─────────────────────────────────────────────
  {
    id: 'BMH-40',
    slug: 'marathon-ranger-2bed-1bath-single-wide',
    title: 'The Ranger',
    manufacturer: 'Texas Homes Direct',
    model: 'Ranger',
    dimensions: '18x50',
    price: 0,
    beds: 2,
    baths: 1,
    sqft: 850,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Ranger-FloorPlan.webp',
    ],
    features: ['Optional Deck', '2 Bed / 1 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Ranger is an 18x50 singlewide with 850 square feet, 2 beds and 1 bath. Optional deck. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 950,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Ranger-FloorPlan.webp',
  },
  // ─── BMH-41 · The Daniel ─────────────────────────────────────────────
  {
    id: 'BMH-41',
    slug: 'marathon-daniel-1bed-1bath-park-model',
    title: 'The Daniel',
    manufacturer: 'Texas Homes Direct',
    model: 'Daniel',
    dimensions: "11'8\" x 34'",
    price: 0,
    beds: 1,
    baths: 1,
    sqft: 399,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-chapman/Chapman-Hero.png',
      '/homes/the-daniel/Daniel-Body-2.webp',
      '/homes/the-daniel/Daniel-Body-3.webp',
      '/homes/the-daniel/Daniel-Body-4.webp',
      '/homes/the-daniel/Daniel-Body-5.webp',
      '/homes/the-daniel/Daniel-Body-6.webp',
      '/homes/the-daniel/Daniel-Body-7.webp',
      '/homes/the-daniel/Daniel-Body-8.webp',
      '/homes/the-daniel/Daniel-Body-9.webp',
      '/homes/the-daniel/Daniel-Body-10.webp',
      '/homes/the-daniel/Daniel-Body-11.webp',
      '/homes/the-daniel/Daniel-Body-12.webp',
    ],
    features: ['Park Model/Tiny Home', 'Front Porch', '1 Bed / 1 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Daniel is an 11\'8" x 34\' park model / tiny home, 399 square feet, 1 bed and 1 bath. Includes a front porch.',
    monthlyPayment: 800,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Daniel-FloorPlan.png',
  },
  // ─── BMH-42 · The Chapman ─────────────────────────────────────────────
  {
    id: 'BMH-42',
    slug: 'marathon-chapman-1bed-1bath-park-model',
    title: 'The Chapman',
    manufacturer: 'Texas Homes Direct',
    model: 'Chapman',
    dimensions: "15x32'8\"",
    price: 0,
    beds: 1,
    baths: 1,
    sqft: 399,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-daniel/Daniel-Body-1.png',
      '/homes/the-chapman/IMG_9474.webp',
      '/homes/the-chapman/IMG_9479.webp',
      '/homes/the-chapman/IMG_9484.webp',
      '/homes/the-chapman/IMG_9577.webp',
      '/homes/the-chapman/IMG_9579.webp',
      '/homes/the-chapman/IMG_9584.webp',
      '/homes/the-chapman/IMG_9597.webp',
      '/homes/the-chapman/IMG_9599.webp',
      '/homes/the-chapman/IMG_9604.webp',
      '/homes/the-chapman/IMG_9609.webp',
      '/homes/the-chapman/IMG_9614.webp',
      '/homes/the-chapman/IMG_9619.webp',
      '/homes/the-chapman/IMG_9624.webp',
      '/homes/the-chapman/IMG_9632.webp',
      '/homes/the-chapman/IMG_9634.webp',
    ],
    features: ['Park Model/Tiny Home', 'Front Porch', '1 Bed / 1 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Chapman is a 15x32\'8" park model / tiny home, 399 square feet, 1 bed and 1 bath. Includes a front porch.',
    monthlyPayment: 800,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Chapman-FloorPlan.webp',
  },
  // ─── BMH-43 · The Pearland ─────────────────────────────────────────────
  {
    id: 'BMH-43',
    slug: 'marathon-pearland-3bed-2bath-single-wide',
    title: 'The Pearland',
    manufacturer: 'Texas Homes Direct',
    model: 'Pearland',
    dimensions: '16x76',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1140,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-pearland/918F558B-6E95-44EF-9CD5-E240C3BBDDBE.png',
      '/homes/the-pearland/IMG_7164.webp',
      '/homes/the-pearland/image-5.webp',
      '/homes/the-pearland/image-6.webp',
      '/homes/the-pearland/image.webp',
      '/homes/the-pearland/IMG_7078.webp',
      '/homes/the-pearland/IMG_7093.webp',
      '/homes/the-pearland/IMG_7098.webp',
      '/homes/the-pearland/IMG_7103.webp',
      '/homes/the-pearland/IMG_7108.webp',
      '/homes/the-pearland/IMG_7118.webp',
      '/homes/the-pearland/IMG_7128.webp',
      '/homes/the-pearland/IMG_7146.webp',
      '/homes/the-pearland/IMG_7151.webp',
      '/homes/the-pearland/IMG_7153.webp',
    ],
    features: ['3 Bed / 2 Bath', '1,140 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Pearland is a 16x76 singlewide with 1,140 square feet, 3 beds and 2 baths.',
    monthlyPayment: 1050,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Pearland-FloorPlan.webp',
  },
  // ─── BMH-44 · The Breckenridge ─────────────────────────────────────────────
  {
    id: 'BMH-44',
    slug: 'marathon-breckenridge-3bed-2bath-single-wide',
    title: 'The Breckenridge',
    manufacturer: 'Texas Homes Direct',
    model: 'Breckenridge',
    dimensions: '14x72',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 984,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Breckenridge-FloorPlan.webp',
    ],
    features: ['3 Bed / 2 Bath', '984 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Breckenridge is a 14x72 singlewide with 984 square feet, 3 beds and 2 baths. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 950,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Breckenridge-FloorPlan.webp',
  },
  // ─── BMH-45 · The Longview ─────────────────────────────────────────────
  {
    id: 'BMH-45',
    slug: 'marathon-longview-3bed-2bath-single-wide',
    title: 'The Longview',
    manufacturer: 'Texas Homes Direct',
    model: 'Longview',
    dimensions: '16x72',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1080,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Longview-FloorPlan.webp',
    ],
    features: ['Multiple Kitchen Options', '3 Bed / 2 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Longview is a 16x72 singlewide with 1,080 square feet, 3 beds and 2 baths. Multiple kitchen layout options. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 950,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Longview-FloorPlan.webp',
  },
  // ─── BMH-46 · The Dawson ─────────────────────────────────────────────
  {
    id: 'BMH-46',
    slug: 'marathon-dawson-4bed-2bath-double-wide',
    title: 'The Dawson',
    manufacturer: 'Texas Homes Direct',
    model: 'Dawson',
    dimensions: '28x64',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 1749,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Dawson-FloorPlan.webp',
    ],
    features: ['5th Bedroom Option', 'Glamour Bathroom Option', '4 Bed / 2 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Dawson is a 28x64 doublewide with 1,749 square feet, 4 beds and 2 baths. 5th bedroom and glamour bathroom options. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 1500,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Dawson-FloorPlan.webp',
  },
  // ─── BMH-47 · The Lanny ─────────────────────────────────────────────
  {
    id: 'BMH-47',
    slug: 'marathon-lanny-1bed-1bath-park-model',
    title: 'The Lanny',
    manufacturer: 'Texas Homes Direct',
    model: 'Lanny',
    dimensions: '12x33',
    price: 0,
    beds: 1,
    baths: 1,
    sqft: 396,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-lanny/7ADF26C5-4FB1-419E-8807-A72A63DB5F18.png',
      '/homes/the-lanny/IMG_9459.webp',
      '/homes/the-lanny/IMG_9464.webp',
      '/homes/the-lanny/IMG_9489.webp',
      '/homes/the-lanny/IMG_9494.webp',
      '/homes/the-lanny/IMG_9517.webp',
      '/homes/the-lanny/IMG_9527.webp',
      '/homes/the-lanny/IMG_9529.webp',
      '/homes/the-lanny/IMG_9539.webp',
      '/homes/the-lanny/IMG_9547.webp',
      '/homes/the-lanny/IMG_9549.webp',
      '/homes/the-lanny/IMG_9559.webp',
      '/homes/the-lanny/IMG_9569-1536x1024.webp',
    ],
    features: ['Park Model/Tiny Home', 'Wrap-Around Porch', '1 Bed / 1 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Lanny is a 12x33 park model / tiny home, 396 square feet, 1 bed and 1 bath. Good fit for a weekend place, guest quarters, or downsizing.',
    monthlyPayment: 800,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Lanny-FloorPlan.webp',
  },
  // ─── BMH-48 · The Fisher ─────────────────────────────────────────────
  {
    id: 'BMH-48',
    slug: 'marathon-fisher-3bed-2bath-double-wide',
    title: 'The Fisher',
    manufacturer: 'Texas Homes Direct',
    model: 'Fisher',
    dimensions: '28x68',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1859,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Fisher-FloorPlan.webp',
    ],
    features: ['4th Bedroom Option', '3rd Bathroom Option', '3 Bed / 2 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Fisher is a 28x68 doublewide with 1,859 square feet, 3 beds and 2 baths. 4th bedroom and 3rd bathroom options. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 1575,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Fisher-FloorPlan.webp',
  },
  // ─── BMH-49 · The Cisco ─────────────────────────────────────────────
  {
    id: 'BMH-49',
    slug: 'marathon-cisco-2bed-2bath-single-wide',
    title: 'The Cisco',
    manufacturer: 'Texas Homes Direct',
    model: 'Cisco',
    dimensions: '16x56',
    price: 0,
    beds: 2,
    baths: 2,
    sqft: 840,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Cisco-FloorPlan.webp',
    ],
    features: ['Multiple Kitchen Options', '2 Bed / 2 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Cisco is a 16x56 singlewide with 840 square feet, 2 beds and 2 baths. Multiple kitchen layout options. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 850,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Cisco-FloorPlan.webp',
  },
  // ─── BMH-50 · The Temple ─────────────────────────────────────────────
  {
    id: 'BMH-50',
    slug: 'marathon-temple-3bed-2bath-single-wide',
    title: 'The Temple',
    manufacturer: 'Texas Homes Direct',
    model: 'Temple',
    dimensions: '18x76',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1156,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-temple/5EA4F89E-9B6D-4F21-80E8-ACAB5163349D.png',
      '/homes/the-temple/IMG_0004.webp',
      '/homes/the-temple/IMG_0134.webp',
      '/homes/the-temple/IMG_0139.webp',
      '/homes/the-temple/IMG_0149-2048x1366.webp',
      '/homes/the-temple/IMG_0154.webp',
      '/homes/the-temple/IMG_0159.webp',
      '/homes/the-temple/IMG_0164.webp',
      '/homes/the-temple/IMG_0171.webp',
      '/homes/the-temple/IMG_0189-2048x1366.webp',
      '/homes/the-temple/IMG_0199-2048x1366.webp',
    ],
    features: ["8' Front Porch", 'Alternate Kitchen Option', '3 Bed / 2 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Temple is an 18x76 singlewide with 1,156 square feet, 3 beds and 2 baths. Comes with an 8\' front porch and an alternate kitchen layout option.',
    monthlyPayment: 1490,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Temple-FloorPlan.webp',
  },
  // ─── BMH-51 · The Grayson ─────────────────────────────────────────────
  {
    id: 'BMH-51',
    slug: 'marathon-grayson-4bed-2bath-double-wide',
    title: 'The Grayson',
    manufacturer: 'Texas Homes Direct',
    model: 'Grayson',
    dimensions: '28x76',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 2077,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-grayson/Image.jpg',
      '/homes/the-grayson/IMG_0789.webp',
      '/homes/the-grayson/IMG_0802.webp',
      '/homes/the-grayson/IMG_0807.webp',
      '/homes/the-grayson/IMG_0817.webp',
      '/homes/the-grayson/IMG_0822.webp',
      '/homes/the-grayson/IMG_0832.webp',
      '/homes/the-grayson/IMG_0857.webp',
      '/homes/the-grayson/IMG_0867.webp',
      '/homes/the-grayson/IMG_0872.webp',
      '/homes/the-grayson/IMG_0877.webp',
      '/homes/the-grayson/IMG_0897.webp',
      '/homes/the-grayson/IMG_0899.webp',
      '/homes/the-grayson/IMG_0904.webp',
    ],
    features: ['5th Bedroom Option', '3rd Bathroom Option', '4 Bed / 2 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Grayson is a 28x76 doublewide with 2,077 square feet, 4 beds and 2 baths. Options for a 5th bedroom and a 3rd bathroom if you need the extra room.',
    monthlyPayment: 1700,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Grayson-FloorPlan.webp',
  },
  // ─── BMH-52 · The Darrell ─────────────────────────────────────────────
  {
    id: 'BMH-52',
    slug: 'marathon-darrell-1bed-1bath-park-model',
    title: 'The Darrell',
    manufacturer: 'Texas Homes Direct',
    model: 'Darrell',
    dimensions: '12x33',
    price: 0,
    beds: 1,
    baths: 1,
    sqft: 396,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Darrell-FloorPlan.webp',
    ],
    features: ['Park Model/Tiny Home', 'Front Porch Option', '1 Bed / 1 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Darrell is a 12x33 park model / tiny home, 396 square feet, 1 bed and 1 bath. Front porch option. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 800,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Darrell-FloorPlan.webp',
  },
  // ─── BMH-53 · The Beaumont ─────────────────────────────────────────────
  {
    id: 'BMH-53',
    slug: 'marathon-beaumont-3bed-2bath-single-wide',
    title: 'The Beaumont',
    manufacturer: 'Texas Homes Direct',
    model: 'Beaumont',
    dimensions: '14x68',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 929,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/floorplans/Beaumont-FloorPlan.webp',
    ],
    features: ['3 Bed / 2 Bath', '929 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Beaumont is a 14x68 singlewide with 929 square feet, 3 beds and 2 baths. Photography from Texas Homes Direct still pending.',
    monthlyPayment: 900,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/floorplans/Beaumont-FloorPlan.webp',
  },
  // ─── BMH-54 · The Pronghorn ─────────────────────────────────────────────
  {
    id: 'BMH-54',
    slug: 'fleetwood-pronghorn-4bed-2bath-double-wide',
    title: 'The Pronghorn',
    manufacturer: 'Fleetwood',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 1920,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-pronghorn/Image.jpeg',
      '/homes/the-pronghorn/IMG_0876.jpeg',
      '/homes/the-pronghorn/IMG_0877.jpeg',
      '/homes/the-pronghorn/IMG_0878.jpeg',
      '/homes/the-pronghorn/IMG_0879.jpeg',
      '/homes/the-pronghorn/IMG_0880.jpeg',
      '/homes/the-pronghorn/IMG_0881.jpeg',
      '/homes/the-pronghorn/IMG_0882.jpeg',
      '/homes/the-pronghorn/IMG_0883.jpeg',
      '/homes/the-pronghorn/IMG_0884.jpeg',
      '/homes/the-pronghorn/IMG_0885.jpeg',
      '/homes/the-pronghorn/IMG_0886.jpeg',
      '/homes/the-pronghorn/IMG_0887.jpeg',
      '/homes/the-pronghorn/IMG_0888.jpeg',
      '/homes/the-pronghorn/IMG_0889.jpeg',
    ],
    features: ['4 Bed / 2 Bath', '1,920 Sq Ft', 'Option of 5 Bed / 3 Bath', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Pronghorn is a 1,920 square foot doublewide with 4 beds and 2 baths, with the option to configure as 5 beds and 3 baths.',
    monthlyPayment: 1250,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-pronghorn/Pronghorn-FloorPlan.png',
  },
  // ─── BMH-55 · The Armadillo ─────────────────────────────────────────────
  {
    id: 'BMH-55',
    slug: 'fleetwood-armadillo-3bed-2bath',
    title: 'The Armadillo',
    manufacturer: 'Fleetwood',
    model: 'Armadillo',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1140,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-armadillo/IMG_0843.png',
      '/homes/the-armadillo/IMG_0847.jpg',
      '/homes/the-armadillo/IMG_0848.jpg',
      '/homes/the-armadillo/IMG_0849.jpg',
      '/homes/the-armadillo/IMG_0850.jpg',
      '/homes/the-armadillo/IMG_0851.jpg',
      '/homes/the-armadillo/IMG_0853.jpg',
      '/homes/the-armadillo/IMG_0854.jpg',
      '/homes/the-armadillo/IMG_0855.jpg',
      '/homes/the-armadillo/IMG_0857.jpg',
      '/homes/the-armadillo/IMG_0858.jpg',
    ],
    features: ['3 Bed / 2 Bath', '1,140 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Armadillo is a 1,140 square foot Fleetwood home with 3 beds and 2 baths.',
    monthlyPayment: 950,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-armadillo/Armadillo-FloorPlan.png',
  },
  // ─── BMH-56 · The Road Runner ─────────────────────────────────────────────
  {
    id: 'BMH-56',
    slug: 'fleetwood-roadrunner-3bed-2bath',
    title: 'The Road Runner',
    manufacturer: 'Fleetwood',
    model: 'Road Runner',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1493,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-road-runner/IMG_0750.jpg',
      '/homes/the-road-runner/IMG_0863.jpg',
      '/homes/the-road-runner/IMG_0865.jpg',
      '/homes/the-road-runner/IMG_0866.jpg',
      '/homes/the-road-runner/IMG_0867.jpg',
      '/homes/the-road-runner/IMG_0868.jpg',
      '/homes/the-road-runner/IMG_0869.jpg',
      '/homes/the-road-runner/IMG_0870.jpg',
      '/homes/the-road-runner/IMG_0871.jpg',
      '/homes/the-road-runner/IMG_0872.jpg',
    ],
    features: ['3 Bed / 2 Bath', '1,493 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Road Runner is a 1,493 square foot Fleetwood home with 3 beds and 2 baths.',
    monthlyPayment: 1000,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-road-runner/RoadRunner-FloorPlan.png',
  },
  // ─── BMH-57 · The Bobcat ─────────────────────────────────────────────
  {
    id: 'BMH-57',
    slug: 'fleetwood-bobcat-3bed-2bath-single-wide',
    title: 'The Bobcat',
    manufacturer: 'Fleetwood',
    model: 'Mya',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 924,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-bobcat/IMG_0779.jpeg',
      '/homes/the-bobcat/IMG_0891.jpeg',
    ],
    features: ['3 Bed / 2 Bath', '924 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Bobcat is a 924 square foot singlewide with 3 beds and 2 baths.',
    monthlyPayment: 799,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-bobcat/Bobcat-FloorPlan.png',
  },
  // ─── BMH-58 · The Javelina ─────────────────────────────────────────────
  {
    id: 'BMH-58',
    slug: 'fleetwood-javelina-1bed-1bath-single-wide',
    title: 'The Javelina',
    manufacturer: 'Fleetwood',
    model: 'Tia',
    price: 0,
    beds: 1,
    baths: 1,
    sqft: 546,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-javelina/hero.png',
    ],
    features: ['1 Bed / 1 Bath', '546 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Javelina is a compact 546 square foot Fleetwood singlewide with 1 bed and 1 bath.',
    monthlyPayment: 650,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-javelina/Javelina-FloorPlan.png',
  },
  // ─── BMH-59 · The Axis ─────────────────────────────────────────────
  {
    id: 'BMH-59',
    slug: 'fleetwood-axis-3bed-2bath-double-wide',
    title: 'The Axis',
    manufacturer: 'Fleetwood',
    model: '28683p',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1600,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-axis-fleetwood/img-01.png',
      '/homes/the-axis-fleetwood/img-02.png',
      '/homes/the-axis-fleetwood/img-03.png',
      '/homes/the-axis-fleetwood/img-04.png',
      '/homes/the-axis-fleetwood/img-05.png',
      '/homes/the-axis-fleetwood/img-06.png',
      '/homes/the-axis-fleetwood/img-07.png',
      '/homes/the-axis-fleetwood/img-08.png',
      '/homes/the-axis-fleetwood/img-09.png',
      '/homes/the-axis-fleetwood/img-10.png',
      '/homes/the-axis-fleetwood/img-11.png',
      '/homes/the-axis-fleetwood/img-12.png',
      '/homes/the-axis-fleetwood/img-13.png',
    ],
    features: ['3 Bed / 2 Bath', '1,600 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Axis is a 1,600 square foot Fleetwood doublewide with 3 beds and 2 baths.',
    monthlyPayment: 1100,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-axis-fleetwood/Axis-FloorPlan.png',
  },
  // ─── BMH-60 · The Moose ─────────────────────────────────────────────
  {
    id: 'BMH-60',
    slug: 'fleetwood-moose-4bed-2bath-double-wide',
    title: 'The Moose',
    manufacturer: 'Fleetwood',
    model: '3268u',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 2040,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-moose/hero.jpeg',
    ],
    features: ['4 Bed / 2 Bath', '2,040 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Moose is a 2,040 square foot Fleetwood doublewide with 4 beds and 2 baths.',
    monthlyPayment: 1499,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-moose/Moose-FloorPlan.webp',
  },
  // ─── BMH-61 · The Jack Rabbit ─────────────────────────────────────────────
  {
    id: 'BMH-61',
    slug: 'fleetwood-jackrabbit-3bed-2bath-double-wide',
    title: 'The Jack Rabbit',
    manufacturer: 'Fleetwood',
    model: '28483p',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1280,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-jack-rabbit/img-01.jpeg',
      '/homes/the-jack-rabbit/img-02.png',
      '/homes/the-jack-rabbit/img-03.png',
      '/homes/the-jack-rabbit/img-04.png',
      '/homes/the-jack-rabbit/img-05.png',
      '/homes/the-jack-rabbit/img-06.png',
      '/homes/the-jack-rabbit/img-07.png',
      '/homes/the-jack-rabbit/img-09.png',
      '/homes/the-jack-rabbit/img-10.png',
      '/homes/the-jack-rabbit/img-11.png',
      '/homes/the-jack-rabbit/img-12.png',
    ],
    features: ['3 Bed / 2 Bath', '1,280 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Jack Rabbit is a 1,280 square foot Fleetwood doublewide with 3 beds and 2 baths.',
    monthlyPayment: 1100,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-jack-rabbit/JackRabbit-FloorPlan.png',
  },
  // ─── BMH-62 · The PereDavid ─────────────────────────────────────────────
  {
    id: 'BMH-62',
    slug: 'fleetwood-peredavid-3bed-2bath-double-wide',
    title: 'The PereDavid',
    manufacturer: 'Fleetwood',
    model: 'Vantage',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1680,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-peredavid/img-01.png',
      '/homes/the-peredavid/img-02.png',
      '/homes/the-peredavid/img-03.png',
      '/homes/the-peredavid/img-04.png',
      '/homes/the-peredavid/img-05.png',
      '/homes/the-peredavid/img-06.png',
      '/homes/the-peredavid/img-07.png',
      '/homes/the-peredavid/img-08.png',
      '/homes/the-peredavid/img-09.png',
      '/homes/the-peredavid/img-10.png',
      '/homes/the-peredavid/img-11.png',
      '/homes/the-peredavid/img-12.png',
    ],
    features: ['3 Bed / 2 Bath', '1,680 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The PereDavid is a 1,680 square foot Fleetwood doublewide with 3 beds and 2 baths.',
    monthlyPayment: 1235,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    floorplanUrl: '/homes/the-peredavid/PereDavid-FloorPlan.png',
    status: 'Active',
  },
  // ─── BMH-63 · The Badger ─────────────────────────────────────────────
  {
    id: 'BMH-63',
    slug: 'fleetwood-badger-3bed-2bath-double-wide',
    title: 'The Badger',
    manufacturer: 'Fleetwood',
    model: 'vivid',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1600,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-badger/img-01.png',
      '/homes/the-badger/img-02.png',
      '/homes/the-badger/img-03.png',
      '/homes/the-badger/img-04.png',
      '/homes/the-badger/img-05.png',
      '/homes/the-badger/img-06.png',
      '/homes/the-badger/img-07.png',
      '/homes/the-badger/img-08.png',
      '/homes/the-badger/img-09.png',
      '/homes/the-badger/img-10.png',
      '/homes/the-badger/img-11.png',
      '/homes/the-badger/img-12.png',
    ],
    features: ['3 Bed / 2 Bath', '1,600 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Badger is a 1,600 square foot Fleetwood doublewide with 3 beds and 2 baths.',
    monthlyPayment: 1250,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-badger/Badger-FloorPlan.png',
  },
  // ─── BMH-64 · The Dove (Fleetwood) ─────────────────────────────────────────────
  {
    id: 'BMH-64',
    slug: 'fleetwood-dove-3bed-2bath-single-wide',
    title: 'The Dove',
    manufacturer: 'Fleetwood',
    model: 'Nina',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1216,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-dove-fleetwood/img-01.jpeg',
      '/homes/the-dove-fleetwood/img-02.png',
      '/homes/the-dove-fleetwood/img-03.png',
      '/homes/the-dove-fleetwood/img-04.png',
      '/homes/the-dove-fleetwood/img-05.png',
    ],
    features: ['3 Bed / 2 Bath', '1,216 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Dove is a 1,216 square foot Fleetwood singlewide with 3 beds and 2 baths.',
    monthlyPayment: 899,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-dove-fleetwood/Dove-FloorPlan.png',
  },
  // ─── BMH-65 · The Coyote ─────────────────────────────────────────────
  {
    id: 'BMH-65',
    slug: 'fleetwood-coyote-2bed-2bath-single-wide',
    title: 'The Coyote',
    manufacturer: 'Fleetwood',
    model: 'Talia',
    price: 0,
    beds: 2,
    baths: 2,
    sqft: 820,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-coyote/Coyote-FloorPlan.png',
    ],
    features: ['2 Bed / 2 Bath', '820 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Coyote is an 820 square foot Fleetwood singlewide with 2 beds and 2 baths. Photography still pending.',
    monthlyPayment: 750,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-coyote/Coyote-FloorPlan.png',
  },
  // ─── BMH-66 · The Rattlesnake ─────────────────────────────────────────────
  {
    id: 'BMH-66',
    slug: 'fleetwood-rattlesnake-3bed-2bath-single-wide',
    title: 'The Rattlesnake',
    manufacturer: 'Fleetwood',
    model: '1676u',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1178,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-rattlesnake/img-01.png',
      '/homes/the-rattlesnake/img-02.png',
      '/homes/the-rattlesnake/img-03.png',
      '/homes/the-rattlesnake/img-04.png',
      '/homes/the-rattlesnake/img-05.png',
      '/homes/the-rattlesnake/img-06.png',
      '/homes/the-rattlesnake/img-07.png',
      '/homes/the-rattlesnake/img-08.png',
    ],
    features: ['3 Bed / 2 Bath', '1,178 Sq Ft', 'Delivery', 'Setup', 'AC', 'Trim Out', 'Wood Steps', 'Tax', 'Title'],
    description:
      'The Rattlesnake is a 1,178 square foot Fleetwood singlewide with 3 beds and 2 baths.',
    monthlyPayment: 950,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    floorplanUrl: '/homes/the-rattlesnake/Rattlesnake-FloorPlan.png',
  },
]

export const featuredListings = sampleListings.filter((l) => l.featured && l.status === 'Active')
export const activeListings = sampleListings.filter(
  (l) => l.status === 'Active' || l.status === 'Repo Deal',
)
