export interface Listing {
  id: string
  slug: string
  title: string
  price: number          // 0 = contact for pricing
  beds: number
  baths: number
  sqft: number
  year: number
  type: 'new' | 'repo'
  wideType?: 'Single Wide' | 'Double Wide' | 'Triple Wide'
  region: 'South TX' | 'Central TX' | 'West TX' | 'North TX' | 'East TX'
  city: string
  images: string[]
  features: string[]
  description: string
  monthlyPayment: number
  downPayment: number
  available: boolean
  hudCertified: boolean
  featured?: boolean
  manufacturer?: string
  model?: string
  dimensions?: string
  matterportUrl?: string
  notionId?: string
  status?: 'Active' | 'Pending' | 'Sold' | 'Coming Soon' | 'Repo Deal'
  floorplanUrl?: string
}

export const sampleListings: Listing[] = [
  // ─── BMH-1 · The Pigeon ────────────────────────────────────────────
  {
    id: 'BMH-1',
    slug: 'marathon-pigeon-3bed-2bath-double-wide',
    title: 'The Pigeon',
    manufacturer: 'Marathon Homes',
    model: 'Archer',
    dimensions: '28x44',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1232,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-pigeon/Marathon-Archer-1.jpeg',
      '/homes/the-pigeon/Marathon-Archer-3.jpeg',
      '/homes/the-pigeon/Marathon-Archer-4.jpeg',
      '/homes/the-pigeon/Marathon-Archer-6.jpeg',
      '/homes/the-pigeon/Marathon-Archer-5.jpeg',
      '/homes/the-pigeon/Marathon-Archer-7.jpeg',
      '/homes/the-pigeon/Marathon-Archer-8.jpeg',
      '/homes/the-pigeon/Marathon-Archer-2_(1).jpeg',
      '/homes/the-pigeon/Marathon-Archer-1_(1).jpeg',
    ],
    features: ['Open Concept', 'Kitchen Island', 'Walk-in Closet'],
    description:
      'The Pigeon is a well-designed doublewide manufactured home offering approximately 1,232 square feet of living space, featuring three bedrooms and two bathrooms in a practical single-story layout. Its open-concept design connects the living, dining, and kitchen areas to create an easy flow for everyday living and entertaining, while the centrally located kitchen serves as a functional hub.',
    monthlyPayment: 1200,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: undefined,
    floorplanUrl: '/homes/floorplans/Pigeon-FloorPlan.png',
  },

  // ─── BMH-14 · The Dove ─────────────────────────────────────────────
  {
    id: 'BMH-14',
    slug: 'marathon-dove-1bed-1bath-single-wide',
    title: 'The Dove',
    manufacturer: 'Marathon Homes',
    model: 'Dove',
    dimensions: '16x40',
    price: 0,
    beds: 1,
    baths: 1,
    sqft: 472,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-dove/IMG_0895.jpg.jpeg',
      '/homes/the-dove/IMG_0079-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0074-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0069-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0064-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0059-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0054-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0044-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0036-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0034-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0019-1-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0006-scaled.jpg.jpeg',
      '/homes/the-dove/IMG_0004-scaled.jpg.jpeg',
      '/homes/the-dove/cfdc3b97-c652-4392-a7d9-e9393520a4ff-scaled.jpg.jpeg',
      '/homes/the-dove/446a0c32-a24b-4392-9be3-facc862a29be-scaled.jpg.jpeg',
    ],
    features: ['Compact and Efficient', 'Starter Home', 'Affordable Entry Point'],
    description:
      'The Dove is a charming and compact single-wide manufactured home that makes smart, efficient use of 472 square feet. Perfect as a starter home or for those seeking affordable, low-maintenance living in a 16x40 layout.',
    monthlyPayment: 850,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: true,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=bAQiAM7npui&back=1',
    floorplanUrl: '/homes/floorplans/Dove-FloorPlan.jpeg',
  },

  // ─── BMH-15 · The Gadwall ──────────────────────────────────────────
  {
    id: 'BMH-15',
    slug: 'marathon-gadwall-3bed-2bath-double-wide',
    title: 'The Gadwall',
    manufacturer: 'Marathon Homes',
    model: 'Gadwall',
    dimensions: '32x56',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1680,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-gadwall/IMG_0885.jpg.jpeg',
      '/homes/the-gadwall/IMG_1787-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1786-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1785-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1784-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1783-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1782-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1780-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1778-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1777-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1775-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1773-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1772-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1771-2-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1770-scaled.jpg.jpeg',
      '/homes/the-gadwall/IMG_1769-2-scaled.jpg.jpeg',
    ],
    features: ['Open Concept', 'Double Wide', 'Spacious Layout'],
    description:
      'The Gadwall is a spacious and thoughtfully designed double-wide manufactured home that blends comfort with everyday functionality. At 32x56 and 1,680 sq. ft., it offers 3 bedrooms and 2 bathrooms for comfortable family living.',
    monthlyPayment: 1500,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: undefined,
    floorplanUrl: '/homes/floorplans/Gadwall-FloorPlan.jpeg',
  },

  // ─── BMH-16 · The Pintail ──────────────────────────────────────────
  {
    id: 'BMH-16',
    slug: 'marathon-pintail-4bed-2bath-double-wide',
    title: 'The Pintail',
    manufacturer: 'Marathon Homes',
    model: 'Pintail',
    dimensions: '32x64',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 1920,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-pintail/8-Sterling.png',
      '/homes/the-pintail/32644A-reduced-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7053-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7054-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7056-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7057-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7060-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7061-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7064-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7066-scaled.jpg.jpeg',
      '/homes/the-pintail/IMG_7068-scaled.jpg.jpeg',
    ],
    features: ['Spacious Layout', 'Open Concept', 'Stylish Finishes'],
    description:
      'The Pintail is a spacious and stylish manufactured home that thoughtfully combines comfort with modern design. At 32x64 and 1,920 sq. ft., this 4 bedroom, 2 bathroom double-wide delivers excellent space for growing families.',
    monthlyPayment: 1600,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: true,
    status: 'Active',
    matterportUrl: undefined,
    floorplanUrl: '/homes/floorplans/Pintail-FloorPlan.jpeg',
  },

  // ─── BMH-17 · The Spoonbill ────────────────────────────────────────
  {
    id: 'BMH-17',
    slug: 'marathon-spoonbill-3bed-2bath-single-wide',
    title: 'The Spoonbill',
    manufacturer: 'Marathon Homes',
    model: 'Spoonbill',
    dimensions: '16x76',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1140,
    year: 2026,
    type: 'new',
    wideType: 'Single Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-spoonbill/IMG_7169-scaled.jpg.jpeg',
      '/homes/the-spoonbill/image-9-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7170-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7178-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7180-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7185-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7190-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7195-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7200-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7208-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7210-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7215-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7220-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7228-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7230-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7238-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7243-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7245-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7253-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7258-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7263-scaled.jpg.jpeg',
      '/homes/the-spoonbill/IMG_7268-scaled.jpg.jpeg',
    ],
    features: ['Practical Layout', 'Single Wide', 'Comfortable Living'],
    description:
      'The Spoonbill is a beautifully balanced manufactured home that offers both comfort and practicality in a 16x76 single-wide layout. With 1,140 sq. ft., 3 bedrooms, and 2 bathrooms, it delivers solid value for first-time buyers.',
    monthlyPayment: 1000,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=aAk5oxt6cER&back=1',
    floorplanUrl: '/homes/floorplans/Spoonbill-FloorPlan.jpeg',
  },

  // ─── BMH-18 · The Redhead ──────────────────────────────────────────
  {
    id: 'BMH-18',
    slug: 'marathon-redhead-3bed-2bath-double-wide',
    title: 'The Redhead',
    manufacturer: 'Marathon Homes',
    model: 'Redhead',
    dimensions: '32x56',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1680,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-redhead/IMG_0001-scaled.jpg.jpeg',
      '/homes/the-redhead/3ba5543a-6344-4c4d-8af4-a6c8f13c2ce3-scaled.jpg.jpeg',
      '/homes/the-redhead/9cef5aa3-21fd-49df-9f5b-f29d499eb038-scaled.jpg.jpeg',
      '/homes/the-redhead/99a8b129-48eb-4506-8848-37d730ac1e89-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0002-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0009-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0014-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0019-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0029-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0039-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0044-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0049-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0054-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0059-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0064-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0069-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0074-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0079-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0084-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0094-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0099-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0104-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0114-scaled.jpg.jpeg',
      '/homes/the-redhead/IMG_0116-scaled.jpg.jpeg',
    ],
    features: ['Open Concept', 'Double Wide', 'Spacious Bedrooms'],
    description:
      'The Redhead is a beautifully crafted manufactured home that combines spacious, thoughtful design with modern comfort. At 32x56 and 1,680 sq. ft., this 3 bedroom, 2 bathroom double-wide is built for families who want quality without compromise.',
    monthlyPayment: 1500,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=7VkF3t1HMLY&back=1',
    floorplanUrl: '/homes/floorplans/Redhead-FloorPlan.jpeg',
  },

  // ─── BMH-19 · The Wood Duck ────────────────────────────────────────
  {
    id: 'BMH-19',
    slug: 'marathon-woodduck-3bed-2bath-double-wide',
    title: 'The Wood Duck',
    manufacturer: 'Marathon Homes',
    model: 'Wood Duck',
    dimensions: '32x56',
    price: 0,
    beds: 3,
    baths: 2,
    sqft: 1680,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-wood-duck/IMG_0891.jpg.jpeg',
      '/homes/the-wood-duck/IMG_0579-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0584-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0589-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0597-scaled.jpg.jpeg',
      '/homes/the-wood-duck/IMG_0602-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0607-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0609-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0614-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0622-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0627-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0632-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0637-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0642-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0647-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0657-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0662-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0667-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0669-scaled.jpeg',
      '/homes/the-wood-duck/IMG_0677-scaled.jpeg',
    ],
    features: ['Open Concept', 'Double Wide', 'Inviting Layout'],
    description:
      'The Wood Duck is a thoughtfully designed double-wide manufactured home that offers an inviting layout with 3 bedrooms, 2 bathrooms, and 1,680 sq. ft. of living space in a 32x56 footprint.',
    monthlyPayment: 1500,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=XZ7JAYuj8K9&back=1',
    floorplanUrl: '/homes/floorplans/WoodDuck-FloorPlan.jpeg',
  },

  // ─── BMH-20 · The Widgeon ──────────────────────────────────────────
  {
    id: 'BMH-20',
    slug: 'marathon-widgeon-4bed-2bath-double-wide',
    title: 'The Widgeon',
    manufacturer: 'Marathon Homes',
    model: 'Widgeon',
    dimensions: '32x68',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 2040,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-widgeon/2-Stonewall.jpg.jpeg',
      '/homes/the-widgeon/IMG_0682-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0687-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0692-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0697-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0702-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0707-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0712-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0717-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0722-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0724-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0732-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0737-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0739-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0744-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0749-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0757-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0762-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0767-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0769-scaled.jpg.jpeg',
      '/homes/the-widgeon/IMG_0774-scaled.jpg.jpeg',
    ],
    features: ['Spacious Layout', 'Open Concept', 'Double Wide'],
    description:
      'The Widgeon is a spacious, thoughtfully designed double-wide manufactured home that blends comfort with functionality. With 2,040 sq. ft., 4 bedrooms, and 2 bathrooms in a 32x68 layout, it has plenty of room for the whole family.',
    monthlyPayment: 1700,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: false,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=eLwoi66X6qK&back=1',
    floorplanUrl: '/homes/floorplans/Widgeon-FloorPlan.jpeg',
  },

  // ─── BMH-21 · The Mallard ──────────────────────────────────────────
  {
    id: 'BMH-21',
    slug: 'marathon-mallard-4bed-2bath-double-wide',
    title: 'The Mallard',
    manufacturer: 'Marathon Homes',
    model: 'Mallard',
    dimensions: '32x76',
    price: 0,
    beds: 4,
    baths: 2,
    sqft: 2280,
    year: 2026,
    type: 'new',
    wideType: 'Double Wide',
    region: 'South TX',
    city: 'San Antonio',
    images: [
      '/homes/the-mallard/213CCA81-EDC0-4C8C-8804-8B2ACE3E4731.jpg.jpeg',
      '/homes/the-mallard/1a65e343-b855-4512-bad8-199f089d0ff4-scaled.jpg.jpeg',
      '/homes/the-mallard/aaed3281-a103-4cd9-befa-83003f52c769-scaled.jpg.jpeg',
      '/homes/the-mallard/baa0f374-8e96-46a2-ac32-94d1c41b14e4-scaled.jpg.jpeg',
      '/homes/the-mallard/e4abc9c0-8038-408c-bbf1-7d1363c35de3-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0217-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0225-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0230-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0235-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0240-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0242-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0247-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0252-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0257-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0262-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0267-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0275-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0277-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0285-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0287-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0292-scaled.jpg.jpeg',
      '/homes/the-mallard/IMG_0297-scaled.jpg.jpeg',
    ],
    features: ['Generous Layout', 'Open Concept', 'Large Double Wide'],
    description:
      'The Mallard from Marathon Homes is a generous double-wide layout measuring 32x76 feet with 2,280 sq. ft. of living space. Four bedrooms and two bathrooms give families all the room they need.',
    monthlyPayment: 1800,
    downPayment: 0,
    available: true,
    hudCertified: true,
    featured: true,
    status: 'Active',
    matterportUrl: 'https://my.matterport.com/show/?m=XGZhqhubvVW&back=1',
    floorplanUrl: '/homes/floorplans/Mallard-FloorPlan.jpeg',
  },


]

export const featuredListings = sampleListings.filter((l) => l.featured && l.status === 'Active')
export const activeListings = sampleListings.filter(
  (l) => l.status === 'Active' || l.status === 'Repo Deal',
)
